version: 1.0.{build}
image: Visual Studio 2022
configuration: Release
platform: Any CPU
before_build:
- ps: nuget restore
build:
  verbosity: minimal
after_build:
- ps: 7z a WaypointCreatorGen3VS2022.zip $Env:APPVEYOR_BUILD_FOLDER"\WaypointCreatorGen3\bin\Release\*"
artifacts:
- path: WaypointCreatorGen3VS2022.zip
